apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Simple Maven Project With Tests on master
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: read
on:
  push:
    branches:
      - master
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v1
      - name: Setup git credentials
        uses: cloudbees-io/configure-git-global-credentials@v1
      - name: Run tests
        kind: test
        uses: docker://maven:3-eclipse-temurin-21-alpine
        run: |
          mvn -B -ntp test
      - name: Publish test results
        kind: test
        if: ${{always()}}
        uses: cloudbees-io/publish-test-results@v2
        with:
          test-type: junit
          results-path: ./target/surefire-reports
